# Generated by Django 4.2.11 on 2025-11-07 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
